version: "3.9"

services:
  auth-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: auth-mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Strong_Password123!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - auth_mssql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  auth_mssql_data: